# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
addons:
  apt:
    packages:
      - libhdf5-serial-dev
warnings_are_errors: false
language: R
sudo: false
cache: packages
Imports:
  - rflann
  - colorplane
Remotes:
  - YeeJeremy/rflann
  - bbuchsbaum/colorplane
after_success:
  - Rscript -e 'covr::codecov(type="all")'

r_packages:
  - covr
  - devtools

r_check_args: "--as-cran --install-args=--build"
before_deploy:
  - if [[ ${#TRAVIS_TAG} -gt 0 ]]; then R CMD INSTALL --build .; fi;

