# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
Imports: rflann
Remotes: YeeJeremy/rflann
after_success:
  - Rscript -e 'covr::codecov()'

r_packages:
  - covr
  - devtools
