// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// bilateral_weights
NumericMatrix bilateral_weights(int window, double spatial_sigma, double intensity_sigma, NumericVector spacing, double intensity_sd);
RcppExport SEXP _neuroim2_bilateral_weights(SEXP windowSEXP, SEXP spatial_sigmaSEXP, SEXP intensity_sigmaSEXP, SEXP spacingSEXP, SEXP intensity_sdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type window(windowSEXP);
    Rcpp::traits::input_parameter< double >::type spatial_sigma(spatial_sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type intensity_sigma(intensity_sigmaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type spacing(spacingSEXP);
    Rcpp::traits::input_parameter< double >::type intensity_sd(intensity_sdSEXP);
    rcpp_result_gen = Rcpp::wrap(bilateral_weights(window, spatial_sigma, intensity_sigma, spacing, intensity_sd));
    return rcpp_result_gen;
END_RCPP
}
// bilateral_filter_cpp
NumericVector bilateral_filter_cpp(NumericVector arr, IntegerVector mask_idx, int window, double spatial_sigma, double intensity_sigma, NumericVector spacing, double range_scale);
RcppExport SEXP _neuroim2_bilateral_filter_cpp(SEXP arrSEXP, SEXP mask_idxSEXP, SEXP windowSEXP, SEXP spatial_sigmaSEXP, SEXP intensity_sigmaSEXP, SEXP spacingSEXP, SEXP range_scaleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type arr(arrSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type mask_idx(mask_idxSEXP);
    Rcpp::traits::input_parameter< int >::type window(windowSEXP);
    Rcpp::traits::input_parameter< double >::type spatial_sigma(spatial_sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type intensity_sigma(intensity_sigmaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type spacing(spacingSEXP);
    Rcpp::traits::input_parameter< double >::type range_scale(range_scaleSEXP);
    rcpp_result_gen = Rcpp::wrap(bilateral_filter_cpp(arr, mask_idx, window, spatial_sigma, intensity_sigma, spacing, range_scale));
    return rcpp_result_gen;
END_RCPP
}
// bilateral_filter_4d_cpp_par
NumericVector bilateral_filter_4d_cpp_par(NumericVector arr, IntegerVector mask_idx, int spatial_window, int temporal_window, double spatial_sigma, double intensity_sigma, double temporal_sigma, NumericVector spacing, double range_scale);
RcppExport SEXP _neuroim2_bilateral_filter_4d_cpp_par(SEXP arrSEXP, SEXP mask_idxSEXP, SEXP spatial_windowSEXP, SEXP temporal_windowSEXP, SEXP spatial_sigmaSEXP, SEXP intensity_sigmaSEXP, SEXP temporal_sigmaSEXP, SEXP spacingSEXP, SEXP range_scaleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type arr(arrSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type mask_idx(mask_idxSEXP);
    Rcpp::traits::input_parameter< int >::type spatial_window(spatial_windowSEXP);
    Rcpp::traits::input_parameter< int >::type temporal_window(temporal_windowSEXP);
    Rcpp::traits::input_parameter< double >::type spatial_sigma(spatial_sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type intensity_sigma(intensity_sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type temporal_sigma(temporal_sigmaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type spacing(spacingSEXP);
    Rcpp::traits::input_parameter< double >::type range_scale(range_scaleSEXP);
    rcpp_result_gen = Rcpp::wrap(bilateral_filter_4d_cpp_par(arr, mask_idx, spatial_window, temporal_window, spatial_sigma, intensity_sigma, temporal_sigma, spacing, range_scale));
    return rcpp_result_gen;
END_RCPP
}
// build_cgb_graph_cpp
List build_cgb_graph_cpp(NumericVector arr, IntegerVector mask_idx, IntegerVector run_ends, int window, double spatial_sigma, NumericVector spacing, int corr_mode, double corr_param, int topk, int leave_out_run, NumericVector run_weights, bool add_self);
RcppExport SEXP _neuroim2_build_cgb_graph_cpp(SEXP arrSEXP, SEXP mask_idxSEXP, SEXP run_endsSEXP, SEXP windowSEXP, SEXP spatial_sigmaSEXP, SEXP spacingSEXP, SEXP corr_modeSEXP, SEXP corr_paramSEXP, SEXP topkSEXP, SEXP leave_out_runSEXP, SEXP run_weightsSEXP, SEXP add_selfSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type arr(arrSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type mask_idx(mask_idxSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type run_ends(run_endsSEXP);
    Rcpp::traits::input_parameter< int >::type window(windowSEXP);
    Rcpp::traits::input_parameter< double >::type spatial_sigma(spatial_sigmaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type spacing(spacingSEXP);
    Rcpp::traits::input_parameter< int >::type corr_mode(corr_modeSEXP);
    Rcpp::traits::input_parameter< double >::type corr_param(corr_paramSEXP);
    Rcpp::traits::input_parameter< int >::type topk(topkSEXP);
    Rcpp::traits::input_parameter< int >::type leave_out_run(leave_out_runSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type run_weights(run_weightsSEXP);
    Rcpp::traits::input_parameter< bool >::type add_self(add_selfSEXP);
    rcpp_result_gen = Rcpp::wrap(build_cgb_graph_cpp(arr, mask_idx, run_ends, window, spatial_sigma, spacing, corr_mode, corr_param, topk, leave_out_run, run_weights, add_self));
    return rcpp_result_gen;
END_RCPP
}
// build_cgb_graph_nuis_cpp
List build_cgb_graph_nuis_cpp(NumericVector arr, IntegerVector mask_idx, IntegerVector run_ends, int window, double spatial_sigma, NumericVector spacing, int corr_mode, double corr_param, int topk, int leave_out_run, NumericVector run_weights, List Q_list, List sqrtw_list, bool add_self);
RcppExport SEXP _neuroim2_build_cgb_graph_nuis_cpp(SEXP arrSEXP, SEXP mask_idxSEXP, SEXP run_endsSEXP, SEXP windowSEXP, SEXP spatial_sigmaSEXP, SEXP spacingSEXP, SEXP corr_modeSEXP, SEXP corr_paramSEXP, SEXP topkSEXP, SEXP leave_out_runSEXP, SEXP run_weightsSEXP, SEXP Q_listSEXP, SEXP sqrtw_listSEXP, SEXP add_selfSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type arr(arrSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type mask_idx(mask_idxSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type run_ends(run_endsSEXP);
    Rcpp::traits::input_parameter< int >::type window(windowSEXP);
    Rcpp::traits::input_parameter< double >::type spatial_sigma(spatial_sigmaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type spacing(spacingSEXP);
    Rcpp::traits::input_parameter< int >::type corr_mode(corr_modeSEXP);
    Rcpp::traits::input_parameter< double >::type corr_param(corr_paramSEXP);
    Rcpp::traits::input_parameter< int >::type topk(topkSEXP);
    Rcpp::traits::input_parameter< int >::type leave_out_run(leave_out_runSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type run_weights(run_weightsSEXP);
    Rcpp::traits::input_parameter< List >::type Q_list(Q_listSEXP);
    Rcpp::traits::input_parameter< List >::type sqrtw_list(sqrtw_listSEXP);
    Rcpp::traits::input_parameter< bool >::type add_self(add_selfSEXP);
    rcpp_result_gen = Rcpp::wrap(build_cgb_graph_nuis_cpp(arr, mask_idx, run_ends, window, spatial_sigma, spacing, corr_mode, corr_param, topk, leave_out_run, run_weights, Q_list, sqrtw_list, add_self));
    return rcpp_result_gen;
END_RCPP
}
// apply_cgb_graph_cpp
NumericVector apply_cgb_graph_cpp(NumericVector arr, IntegerVector row_ptr, IntegerVector col_ind, NumericVector val, IntegerVector mask_idx, int passes, double lambda);
RcppExport SEXP _neuroim2_apply_cgb_graph_cpp(SEXP arrSEXP, SEXP row_ptrSEXP, SEXP col_indSEXP, SEXP valSEXP, SEXP mask_idxSEXP, SEXP passesSEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type arr(arrSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type row_ptr(row_ptrSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type col_ind(col_indSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type val(valSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type mask_idx(mask_idxSEXP);
    Rcpp::traits::input_parameter< int >::type passes(passesSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(apply_cgb_graph_cpp(arr, row_ptr, col_ind, val, mask_idx, passes, lambda));
    return rcpp_result_gen;
END_RCPP
}
// conn_comp_labels_cpp
List conn_comp_labels_cpp(LogicalVector mask, IntegerVector dims, int connectivity);
RcppExport SEXP _neuroim2_conn_comp_labels_cpp(SEXP maskSEXP, SEXP dimsSEXP, SEXP connectivitySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< LogicalVector >::type mask(maskSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type dims(dimsSEXP);
    Rcpp::traits::input_parameter< int >::type connectivity(connectivitySEXP);
    rcpp_result_gen = Rcpp::wrap(conn_comp_labels_cpp(mask, dims, connectivity));
    return rcpp_result_gen;
END_RCPP
}
// prune_local_maxima_cpp
IntegerVector prune_local_maxima_cpp(NumericMatrix coords, NumericVector vals, double mindist);
RcppExport SEXP _neuroim2_prune_local_maxima_cpp(SEXP coordsSEXP, SEXP valsSEXP, SEXP mindistSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type coords(coordsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type vals(valsSEXP);
    Rcpp::traits::input_parameter< double >::type mindist(mindistSEXP);
    rcpp_result_gen = Rcpp::wrap(prune_local_maxima_cpp(coords, vals, mindist));
    return rcpp_result_gen;
END_RCPP
}
// downsample_3d_cpp
NumericVector downsample_3d_cpp(NumericVector arr, IntegerVector new_dims, IntegerVector old_dims);
RcppExport SEXP _neuroim2_downsample_3d_cpp(SEXP arrSEXP, SEXP new_dimsSEXP, SEXP old_dimsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type arr(arrSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type new_dims(new_dimsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type old_dims(old_dimsSEXP);
    rcpp_result_gen = Rcpp::wrap(downsample_3d_cpp(arr, new_dims, old_dims));
    return rcpp_result_gen;
END_RCPP
}
// downsample_4d_cpp
NumericVector downsample_4d_cpp(NumericVector arr, IntegerVector new_dims, IntegerVector old_dims);
RcppExport SEXP _neuroim2_downsample_4d_cpp(SEXP arrSEXP, SEXP new_dimsSEXP, SEXP old_dimsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type arr(arrSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type new_dims(new_dimsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type old_dims(old_dimsSEXP);
    rcpp_result_gen = Rcpp::wrap(downsample_4d_cpp(arr, new_dims, old_dims));
    return rcpp_result_gen;
END_RCPP
}
// fast_multilayer_laplacian_enhancement_masked
NumericVector fast_multilayer_laplacian_enhancement_masked(NumericVector img, LogicalVector mask, int k, int patch_size, int search_radius, double h, List mapping_params, bool use_normalization_free);
RcppExport SEXP _neuroim2_fast_multilayer_laplacian_enhancement_masked(SEXP imgSEXP, SEXP maskSEXP, SEXP kSEXP, SEXP patch_sizeSEXP, SEXP search_radiusSEXP, SEXP hSEXP, SEXP mapping_paramsSEXP, SEXP use_normalization_freeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type img(imgSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type mask(maskSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type patch_size(patch_sizeSEXP);
    Rcpp::traits::input_parameter< int >::type search_radius(search_radiusSEXP);
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    Rcpp::traits::input_parameter< List >::type mapping_params(mapping_paramsSEXP);
    Rcpp::traits::input_parameter< bool >::type use_normalization_free(use_normalization_freeSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_multilayer_laplacian_enhancement_masked(img, mask, k, patch_size, search_radius, h, mapping_params, use_normalization_free));
    return rcpp_result_gen;
END_RCPP
}
// gaussian_blur_sep_cpp
NumericVector gaussian_blur_sep_cpp(NumericVector arr, IntegerVector mask_idx, int window, double sigma, NumericVector spacing, bool normalize, bool full_mask);
RcppExport SEXP _neuroim2_gaussian_blur_sep_cpp(SEXP arrSEXP, SEXP mask_idxSEXP, SEXP windowSEXP, SEXP sigmaSEXP, SEXP spacingSEXP, SEXP normalizeSEXP, SEXP full_maskSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type arr(arrSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type mask_idx(mask_idxSEXP);
    Rcpp::traits::input_parameter< int >::type window(windowSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type spacing(spacingSEXP);
    Rcpp::traits::input_parameter< bool >::type normalize(normalizeSEXP);
    Rcpp::traits::input_parameter< bool >::type full_mask(full_maskSEXP);
    rcpp_result_gen = Rcpp::wrap(gaussian_blur_sep_cpp(arr, mask_idx, window, sigma, spacing, normalize, full_mask));
    return rcpp_result_gen;
END_RCPP
}
// gaussian_blur_sep_4d_cpp
NumericVector gaussian_blur_sep_4d_cpp(NumericVector arr, IntegerVector mask_idx, int window, double sigma, NumericVector spacing, bool normalize, bool full_mask);
RcppExport SEXP _neuroim2_gaussian_blur_sep_4d_cpp(SEXP arrSEXP, SEXP mask_idxSEXP, SEXP windowSEXP, SEXP sigmaSEXP, SEXP spacingSEXP, SEXP normalizeSEXP, SEXP full_maskSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type arr(arrSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type mask_idx(mask_idxSEXP);
    Rcpp::traits::input_parameter< int >::type window(windowSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type spacing(spacingSEXP);
    Rcpp::traits::input_parameter< bool >::type normalize(normalizeSEXP);
    Rcpp::traits::input_parameter< bool >::type full_mask(full_maskSEXP);
    rcpp_result_gen = Rcpp::wrap(gaussian_blur_sep_4d_cpp(arr, mask_idx, window, sigma, spacing, normalize, full_mask));
    return rcpp_result_gen;
END_RCPP
}
// indexToGridCpp
NumericMatrix indexToGridCpp(IntegerVector idx, IntegerVector array_dim);
RcppExport SEXP _neuroim2_indexToGridCpp(SEXP idxSEXP, SEXP array_dimSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type idx(idxSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type array_dim(array_dimSEXP);
    rcpp_result_gen = Rcpp::wrap(indexToGridCpp(idx, array_dim));
    return rcpp_result_gen;
END_RCPP
}
// gridToIndex3DCpp
IntegerVector gridToIndex3DCpp(IntegerVector array_dim, NumericMatrix voxmat);
RcppExport SEXP _neuroim2_gridToIndex3DCpp(SEXP array_dimSEXP, SEXP voxmatSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type array_dim(array_dimSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type voxmat(voxmatSEXP);
    rcpp_result_gen = Rcpp::wrap(gridToIndex3DCpp(array_dim, voxmat));
    return rcpp_result_gen;
END_RCPP
}
// gridToIndexCpp
NumericVector gridToIndexCpp(IntegerVector array_dim, IntegerMatrix voxmat);
RcppExport SEXP _neuroim2_gridToIndexCpp(SEXP array_dimSEXP, SEXP voxmatSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type array_dim(array_dimSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type voxmat(voxmatSEXP);
    rcpp_result_gen = Rcpp::wrap(gridToIndexCpp(array_dim, voxmat));
    return rcpp_result_gen;
END_RCPP
}
// exgridToIndex4DCpp
NumericVector exgridToIndex4DCpp(IntegerVector array_dim, IntegerVector iind, IntegerVector jind, IntegerVector kind, IntegerVector mind);
RcppExport SEXP _neuroim2_exgridToIndex4DCpp(SEXP array_dimSEXP, SEXP iindSEXP, SEXP jindSEXP, SEXP kindSEXP, SEXP mindSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type array_dim(array_dimSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type iind(iindSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type jind(jindSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type kind(kindSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type mind(mindSEXP);
    rcpp_result_gen = Rcpp::wrap(exgridToIndex4DCpp(array_dim, iind, jind, kind, mind));
    return rcpp_result_gen;
END_RCPP
}
// box_nbhd
NumericVector box_nbhd(NumericVector arr, IntegerVector dims, int x, int y, int z, int window, NumericVector out, int slicedim);
RcppExport SEXP _neuroim2_box_nbhd(SEXP arrSEXP, SEXP dimsSEXP, SEXP xSEXP, SEXP ySEXP, SEXP zSEXP, SEXP windowSEXP, SEXP outSEXP, SEXP slicedimSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type arr(arrSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type dims(dimsSEXP);
    Rcpp::traits::input_parameter< int >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type z(zSEXP);
    Rcpp::traits::input_parameter< int >::type window(windowSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type out(outSEXP);
    Rcpp::traits::input_parameter< int >::type slicedim(slicedimSEXP);
    rcpp_result_gen = Rcpp::wrap(box_nbhd(arr, dims, x, y, z, window, out, slicedim));
    return rcpp_result_gen;
END_RCPP
}
// gaussian_weights
NumericVector gaussian_weights(int window, double sigma, NumericVector spacing);
RcppExport SEXP _neuroim2_gaussian_weights(SEXP windowSEXP, SEXP sigmaSEXP, SEXP spacingSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type window(windowSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type spacing(spacingSEXP);
    rcpp_result_gen = Rcpp::wrap(gaussian_weights(window, sigma, spacing));
    return rcpp_result_gen;
END_RCPP
}
// gaussian_blur_cpp
NumericVector gaussian_blur_cpp(NumericVector arr, IntegerVector mask_idx, int window, double sigma, NumericVector spacing, bool normalize);
RcppExport SEXP _neuroim2_gaussian_blur_cpp(SEXP arrSEXP, SEXP mask_idxSEXP, SEXP windowSEXP, SEXP sigmaSEXP, SEXP spacingSEXP, SEXP normalizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type arr(arrSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type mask_idx(mask_idxSEXP);
    Rcpp::traits::input_parameter< int >::type window(windowSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type spacing(spacingSEXP);
    Rcpp::traits::input_parameter< bool >::type normalize(normalizeSEXP);
    rcpp_result_gen = Rcpp::wrap(gaussian_blur_cpp(arr, mask_idx, window, sigma, spacing, normalize));
    return rcpp_result_gen;
END_RCPP
}
// box_blur
NumericVector box_blur(NumericVector arr, IntegerVector mask_idx, int window);
RcppExport SEXP _neuroim2_box_blur(SEXP arrSEXP, SEXP mask_idxSEXP, SEXP windowSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type arr(arrSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type mask_idx(mask_idxSEXP);
    Rcpp::traits::input_parameter< int >::type window(windowSEXP);
    rcpp_result_gen = Rcpp::wrap(box_blur(arr, mask_idx, window));
    return rcpp_result_gen;
END_RCPP
}
// local_sphere
NumericMatrix local_sphere(int vx, int vy, int vz, double radius, NumericVector spacing, IntegerVector dim);
RcppExport SEXP _neuroim2_local_sphere(SEXP vxSEXP, SEXP vySEXP, SEXP vzSEXP, SEXP radiusSEXP, SEXP spacingSEXP, SEXP dimSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type vx(vxSEXP);
    Rcpp::traits::input_parameter< int >::type vy(vySEXP);
    Rcpp::traits::input_parameter< int >::type vz(vzSEXP);
    Rcpp::traits::input_parameter< double >::type radius(radiusSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type spacing(spacingSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type dim(dimSEXP);
    rcpp_result_gen = Rcpp::wrap(local_sphere(vx, vy, vz, radius, spacing, dim));
    return rcpp_result_gen;
END_RCPP
}
// nifti_read_data_cpp
NumericVector nifti_read_data_cpp(std::string path, double offset, double n, int dtype_code, bool swap, bool gzipped);
RcppExport SEXP _neuroim2_nifti_read_data_cpp(SEXP pathSEXP, SEXP offsetSEXP, SEXP nSEXP, SEXP dtype_codeSEXP, SEXP swapSEXP, SEXP gzippedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type path(pathSEXP);
    Rcpp::traits::input_parameter< double >::type offset(offsetSEXP);
    Rcpp::traits::input_parameter< double >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type dtype_code(dtype_codeSEXP);
    Rcpp::traits::input_parameter< bool >::type swap(swapSEXP);
    Rcpp::traits::input_parameter< bool >::type gzipped(gzippedSEXP);
    rcpp_result_gen = Rcpp::wrap(nifti_read_data_cpp(path, offset, n, dtype_code, swap, gzipped));
    return rcpp_result_gen;
END_RCPP
}
// nifti_write_data_cpp
double nifti_write_data_cpp(std::string path, RawVector header, NumericVector data, int dtype_code, double slope, double inter, bool swap, bool gzipped);
RcppExport SEXP _neuroim2_nifti_write_data_cpp(SEXP pathSEXP, SEXP headerSEXP, SEXP dataSEXP, SEXP dtype_codeSEXP, SEXP slopeSEXP, SEXP interSEXP, SEXP swapSEXP, SEXP gzippedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type path(pathSEXP);
    Rcpp::traits::input_parameter< RawVector >::type header(headerSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type data(dataSEXP);
    Rcpp::traits::input_parameter< int >::type dtype_code(dtype_codeSEXP);
    Rcpp::traits::input_parameter< double >::type slope(slopeSEXP);
    Rcpp::traits::input_parameter< double >::type inter(interSEXP);
    Rcpp::traits::input_parameter< bool >::type swap(swapSEXP);
    Rcpp::traits::input_parameter< bool >::type gzipped(gzippedSEXP);
    rcpp_result_gen = Rcpp::wrap(nifti_write_data_cpp(path, header, data, dtype_code, slope, inter, swap, gzipped));
    return rcpp_result_gen;
END_RCPP
}
// nifti_read_volumes_cpp
NumericMatrix nifti_read_volumes_cpp(std::string path, double offset, double nels, NumericVector vols, int dtype_code, bool swap, bool gzipped);
RcppExport SEXP _neuroim2_nifti_read_volumes_cpp(SEXP pathSEXP, SEXP offsetSEXP, SEXP nelsSEXP, SEXP volsSEXP, SEXP dtype_codeSEXP, SEXP swapSEXP, SEXP gzippedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type path(pathSEXP);
    Rcpp::traits::input_parameter< double >::type offset(offsetSEXP);
    Rcpp::traits::input_parameter< double >::type nels(nelsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type vols(volsSEXP);
    Rcpp::traits::input_parameter< int >::type dtype_code(dtype_codeSEXP);
    Rcpp::traits::input_parameter< bool >::type swap(swapSEXP);
    Rcpp::traits::input_parameter< bool >::type gzipped(gzippedSEXP);
    rcpp_result_gen = Rcpp::wrap(nifti_read_volumes_cpp(path, offset, nels, vols, dtype_code, swap, gzipped));
    return rcpp_result_gen;
END_RCPP
}
// representative_volume_cpp
NumericVector representative_volume_cpp(NumericMatrix mat, std::string representative);
RcppExport SEXP _neuroim2_representative_volume_cpp(SEXP matSEXP, SEXP representativeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type mat(matSEXP);
    Rcpp::traits::input_parameter< std::string >::type representative(representativeSEXP);
    rcpp_result_gen = Rcpp::wrap(representative_volume_cpp(mat, representative));
    return rcpp_result_gen;
END_RCPP
}
// sphere_coords_cpp
IntegerMatrix sphere_coords_cpp(IntegerMatrix off, IntegerVector centre, IntegerVector dim, NumericVector vals, bool use_mask);
RcppExport SEXP _neuroim2_sphere_coords_cpp(SEXP offSEXP, SEXP centreSEXP, SEXP dimSEXP, SEXP valsSEXP, SEXP use_maskSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type off(offSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type centre(centreSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type dim(dimSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type vals(valsSEXP);
    Rcpp::traits::input_parameter< bool >::type use_mask(use_maskSEXP);
    rcpp_result_gen = Rcpp::wrap(sphere_coords_cpp(off, centre, dim, vals, use_mask));
    return rcpp_result_gen;
END_RCPP
}
// sphere_coords_batch_cpp
List sphere_coords_batch_cpp(IntegerMatrix off, IntegerMatrix centres, IntegerVector dim, NumericVector vals, bool use_mask);
RcppExport SEXP _neuroim2_sphere_coords_batch_cpp(SEXP offSEXP, SEXP centresSEXP, SEXP dimSEXP, SEXP valsSEXP, SEXP use_maskSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type off(offSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type centres(centresSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type dim(dimSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type vals(valsSEXP);
    Rcpp::traits::input_parameter< bool >::type use_mask(use_maskSEXP);
    rcpp_result_gen = Rcpp::wrap(sphere_coords_batch_cpp(off, centres, dim, vals, use_mask));
    return rcpp_result_gen;
END_RCPP
}
// sphere_indices_batch_cpp
List sphere_indices_batch_cpp(IntegerMatrix off, IntegerMatrix centres, IntegerVector dim, NumericVector vals, bool use_mask);
RcppExport SEXP _neuroim2_sphere_indices_batch_cpp(SEXP offSEXP, SEXP centresSEXP, SEXP dimSEXP, SEXP valsSEXP, SEXP use_maskSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type off(offSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type centres(centresSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type dim(dimSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type vals(valsSEXP);
    Rcpp::traits::input_parameter< bool >::type use_mask(use_maskSEXP);
    rcpp_result_gen = Rcpp::wrap(sphere_indices_batch_cpp(off, centres, dim, vals, use_mask));
    return rcpp_result_gen;
END_RCPP
}
// sphere_roi_at_cpp
List sphere_roi_at_cpp(IntegerMatrix off, IntegerVector centre, IntegerVector dim, NumericVector vals, bool use_mask);
RcppExport SEXP _neuroim2_sphere_roi_at_cpp(SEXP offSEXP, SEXP centreSEXP, SEXP dimSEXP, SEXP valsSEXP, SEXP use_maskSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type off(offSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type centre(centreSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type dim(dimSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type vals(valsSEXP);
    Rcpp::traits::input_parameter< bool >::type use_mask(use_maskSEXP);
    rcpp_result_gen = Rcpp::wrap(sphere_roi_at_cpp(off, centre, dim, vals, use_mask));
    return rcpp_result_gen;
END_RCPP
}
// series_gather_dense
NumericMatrix series_gather_dense(SEXP data, IntegerVector dim, IntegerMatrix coords);
RcppExport SEXP _neuroim2_series_gather_dense(SEXP dataSEXP, SEXP dimSEXP, SEXP coordsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type data(dataSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type dim(dimSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type coords(coordsSEXP);
    rcpp_result_gen = Rcpp::wrap(series_gather_dense(data, dim, coords));
    return rcpp_result_gen;
END_RCPP
}
// series_gather_sparse
NumericMatrix series_gather_sparse(SEXP data, IntegerVector mapped);
RcppExport SEXP _neuroim2_series_gather_sparse(SEXP dataSEXP, SEXP mappedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type data(dataSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type mapped(mappedSEXP);
    rcpp_result_gen = Rcpp::wrap(series_gather_sparse(data, mapped));
    return rcpp_result_gen;
END_RCPP
}
// sphere_offsets_cpp
IntegerMatrix sphere_offsets_cpp(double radius, NumericVector spacing);
RcppExport SEXP _neuroim2_sphere_offsets_cpp(SEXP radiusSEXP, SEXP spacingSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type radius(radiusSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type spacing(spacingSEXP);
    rcpp_result_gen = Rcpp::wrap(sphere_offsets_cpp(radius, spacing));
    return rcpp_result_gen;
END_RCPP
}
// sphere_at_cpp
IntegerMatrix sphere_at_cpp(IntegerMatrix off, IntegerVector centre, IntegerVector dim, bool base0);
RcppExport SEXP _neuroim2_sphere_at_cpp(SEXP offSEXP, SEXP centreSEXP, SEXP dimSEXP, SEXP base0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type off(offSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type centre(centreSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type dim(dimSEXP);
    Rcpp::traits::input_parameter< bool >::type base0(base0SEXP);
    rcpp_result_gen = Rcpp::wrap(sphere_at_cpp(off, centre, dim, base0));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_neuroim2_bilateral_weights", (DL_FUNC) &_neuroim2_bilateral_weights, 5},
    {"_neuroim2_bilateral_filter_cpp", (DL_FUNC) &_neuroim2_bilateral_filter_cpp, 7},
    {"_neuroim2_bilateral_filter_4d_cpp_par", (DL_FUNC) &_neuroim2_bilateral_filter_4d_cpp_par, 9},
    {"_neuroim2_build_cgb_graph_cpp", (DL_FUNC) &_neuroim2_build_cgb_graph_cpp, 12},
    {"_neuroim2_build_cgb_graph_nuis_cpp", (DL_FUNC) &_neuroim2_build_cgb_graph_nuis_cpp, 14},
    {"_neuroim2_apply_cgb_graph_cpp", (DL_FUNC) &_neuroim2_apply_cgb_graph_cpp, 7},
    {"_neuroim2_conn_comp_labels_cpp", (DL_FUNC) &_neuroim2_conn_comp_labels_cpp, 3},
    {"_neuroim2_prune_local_maxima_cpp", (DL_FUNC) &_neuroim2_prune_local_maxima_cpp, 3},
    {"_neuroim2_downsample_3d_cpp", (DL_FUNC) &_neuroim2_downsample_3d_cpp, 3},
    {"_neuroim2_downsample_4d_cpp", (DL_FUNC) &_neuroim2_downsample_4d_cpp, 3},
    {"_neuroim2_fast_multilayer_laplacian_enhancement_masked", (DL_FUNC) &_neuroim2_fast_multilayer_laplacian_enhancement_masked, 8},
    {"_neuroim2_gaussian_blur_sep_cpp", (DL_FUNC) &_neuroim2_gaussian_blur_sep_cpp, 7},
    {"_neuroim2_gaussian_blur_sep_4d_cpp", (DL_FUNC) &_neuroim2_gaussian_blur_sep_4d_cpp, 7},
    {"_neuroim2_indexToGridCpp", (DL_FUNC) &_neuroim2_indexToGridCpp, 2},
    {"_neuroim2_gridToIndex3DCpp", (DL_FUNC) &_neuroim2_gridToIndex3DCpp, 2},
    {"_neuroim2_gridToIndexCpp", (DL_FUNC) &_neuroim2_gridToIndexCpp, 2},
    {"_neuroim2_exgridToIndex4DCpp", (DL_FUNC) &_neuroim2_exgridToIndex4DCpp, 5},
    {"_neuroim2_box_nbhd", (DL_FUNC) &_neuroim2_box_nbhd, 8},
    {"_neuroim2_gaussian_weights", (DL_FUNC) &_neuroim2_gaussian_weights, 3},
    {"_neuroim2_gaussian_blur_cpp", (DL_FUNC) &_neuroim2_gaussian_blur_cpp, 6},
    {"_neuroim2_box_blur", (DL_FUNC) &_neuroim2_box_blur, 3},
    {"_neuroim2_local_sphere", (DL_FUNC) &_neuroim2_local_sphere, 6},
    {"_neuroim2_nifti_read_data_cpp", (DL_FUNC) &_neuroim2_nifti_read_data_cpp, 6},
    {"_neuroim2_nifti_write_data_cpp", (DL_FUNC) &_neuroim2_nifti_write_data_cpp, 8},
    {"_neuroim2_nifti_read_volumes_cpp", (DL_FUNC) &_neuroim2_nifti_read_volumes_cpp, 7},
    {"_neuroim2_representative_volume_cpp", (DL_FUNC) &_neuroim2_representative_volume_cpp, 2},
    {"_neuroim2_sphere_coords_cpp", (DL_FUNC) &_neuroim2_sphere_coords_cpp, 5},
    {"_neuroim2_sphere_coords_batch_cpp", (DL_FUNC) &_neuroim2_sphere_coords_batch_cpp, 5},
    {"_neuroim2_sphere_indices_batch_cpp", (DL_FUNC) &_neuroim2_sphere_indices_batch_cpp, 5},
    {"_neuroim2_sphere_roi_at_cpp", (DL_FUNC) &_neuroim2_sphere_roi_at_cpp, 5},
    {"_neuroim2_series_gather_dense", (DL_FUNC) &_neuroim2_series_gather_dense, 3},
    {"_neuroim2_series_gather_sparse", (DL_FUNC) &_neuroim2_series_gather_sparse, 2},
    {"_neuroim2_sphere_offsets_cpp", (DL_FUNC) &_neuroim2_sphere_offsets_cpp, 2},
    {"_neuroim2_sphere_at_cpp", (DL_FUNC) &_neuroim2_sphere_at_cpp, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_neuroim2(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
