# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gridToIndex3DCpp <- function(array_dim, voxmat) {
    .Call('_neuroim2_gridToIndex3DCpp', PACKAGE = 'neuroim2', array_dim, voxmat)
}

indexToGridCpp <- function(idx, array_dim) {
    .Call('_neuroim2_indexToGridCpp', PACKAGE = 'neuroim2', idx, array_dim)
}

